# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RiveExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RiveExample
  pod 'RiveRuntime', :git => 'https://github.com/callstack-internal/RiveFramework.git'

end
